version: '3'

services:
  mongodb:
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  bubbletech:
    image: nodejs:14
    build:
      context: .
    environment:
      - PORT=8080
      - NODE_ENV=dev
      - WAIT_HOSTS=mongodb:27017
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - GOOGLE_APPLICATION_CREDENTIALS="./google-credentials.json"
      - MONGOOSE_CONNECT_URL="mongodb://root:password@mongodb:27017"
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./src:/code/src
    depends_on:
      - mongodb
    command: sh -c "/wait && yarn dev"

volumes:
  mongodb_data_container: