version: '3'

services:
  mongodb:
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  bubbletech:
    image: nodejs:14
    build:
      context: .
    environment:
      - PORT=8080
      - WAIT_HOSTS=mongodb:27017
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - .:/code
    depends_on:
      - mongodb
    command: sh -c "/wait && yarn start"

volumes:
  mongodb_data_container: